stages:
  - build
  - push
  - run

variables:
  DOCKER_IMAGE: "nodejs-todo:latest"
  DOCKER_REGISTRY: "docker.io"
  DOCKER_REPO: "dilipshukla517"

before_script:
  - echo "Using Docker version $(docker --version)"

build:
  stage: build
  script:
    - echo 'Building the Docker image'
    - docker build -t ${DOCKER_REGISTRY}/${DOCKER_REPO}/${DOCKER_IMAGE} .

push:
  stage: push
  script:
    - echo 'Pushing the Docker image to Docker Hub registry'
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin ${DOCKER_REGISTRY}
    - docker push ${DOCKER_REGISTRY}/${DOCKER_REPO}/${DOCKER_IMAGE}

run:
  stage: run
  script:
    - echo 'Running the Docker container'
    - docker run -d --name nodejs-todo-container -P ${DOCKER_REGISTRY}/${DOCKER_REPO}/${DOCKER_IMAGE}
